-- SELECT * FROM users;
-- UPDATE users SET salary =7000 WHERE id = 1;
-- SELECT * FROM users;
-- UPDATE users SET salary =7000, email='aarva@dudu.com' WHERE id = 1;
-- SELECT * FROM users;
-- UPDATE users SET salary = 70000 WHERE id=5;
-- SELECT * FROM users;
-- UPDATE users SET name='Aisha Khan' WHERE email='aisha@example.com';
-- SELECT * FROM users;
-- UPDATE users SET salary=salary+10000 WHERE salary<60000;
--  SELECT * FROM users;
UPDATE users SET gender = 'Other' WHERE name='Ishaan';
 SELECT * FROM users;